/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as IndexRouteImport } from './routes/index'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/performance': typeof PerformanceRoute
  '/register': typeof RegisterRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/performance': typeof PerformanceRoute
  '/register': typeof RegisterRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers': typeof ContainersRoute
  '/devices': typeof DevicesRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/performance': typeof PerformanceRoute
  '/register': typeof RegisterRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/containers'
    | '/devices'
    | '/login'
    | '/network'
    | '/performance'
    | '/register'
    | '/servers'
    | '/services'
    | '/storage'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/containers'
    | '/devices'
    | '/login'
    | '/network'
    | '/performance'
    | '/register'
    | '/servers'
    | '/services'
    | '/storage'
    | '/terminal'
  id:
    | '__root__'
    | '/'
    | '/containers'
    | '/devices'
    | '/login'
    | '/network'
    | '/performance'
    | '/register'
    | '/servers'
    | '/services'
    | '/storage'
    | '/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersRoute: typeof ContainersRoute
  DevicesRoute: typeof DevicesRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  PerformanceRoute: typeof PerformanceRoute
  RegisterRoute: typeof RegisterRoute
  ServersRoute: typeof ServersRoute
  ServicesRoute: typeof ServicesRoute
  StorageRoute: typeof StorageRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersRoute: ContainersRoute,
  DevicesRoute: DevicesRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  PerformanceRoute: PerformanceRoute,
  RegisterRoute: RegisterRoute,
  ServersRoute: ServersRoute,
  ServicesRoute: ServicesRoute,
  StorageRoute: StorageRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
